print("addition",2+2)
print("subtraction",5-3)
print("multiplication",4*2)
print("division",8/2)
print("exponentiation",3**3)
print("modulus",10%3)
print("floor division",9//2)
print("complex number",2+3j)
print("absolute value",abs(-7))
print("rounding",round(3.6))